name: Java Build

on:
  workflow_call:

concurrency:
  cancel-in-progress: true
  group: build

env:
  JDK_VERSION: 17

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{matrix.os}}

    defaults:
      run:
        working-directory: java

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{env.JDK_VERSION}}
        uses: actions/setup-java@v3
        with:
          java-version: ${{env.JDK_VERSION}}
          distribution: adopt
          cache: "gradle"

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.7.0
        with:
          gradle-version: wrapper

      - name: Build with Gradle
        run: gradle build
