name: Java

on:
  push:
    paths:
      - ".github/workflows"
      - "java"

concurrency:
  cancel-in-progress: true
  group: java

env:
  JDK_VERSION: 17

jobs:
  build:
    uses: ./.github/workflows/java-build.yml
