name: PR Comment Command

on:
  issue_comment:
    types:
      - created
      - edited

# 参考
# https://akaimo.hatenablog.jp/entry/2020/05/16/101251
# https://buildersbox.corp-sansan.com/entry/2021/02/05/110000

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: set Env value
        env:
          TZ: "Asia/Tokyo" # タイムゾーン指定
        run: |
          echo "process_date=`date '+%Y-%m-%d %H:%M:%S'`" >> "$GITHUB_ENV"

  pr_close:
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body , '/close')

    runs-on: ubuntu-latest

    steps:
      - name: comment
        uses: actions/github-script@v3
        env:
          MESSAGE: |
            "プルリクエストをクローズします"
            "日時：${{env.process_date}}"
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MESSAGE
            })

  test:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          echo "Test"
