name: PR Comment Command

on:
  issue_comment:
    types:
      - created
      - edited

env:
  GH_TOKEN: ${{ github.token }}
  PR_NUMBER: ${{ github.event.issue.number }}

# 参考
# https://akaimo.hatenablog.jp/entry/2020/05/16/101251
# https://buildersbox.corp-sansan.com/entry/2021/02/05/110000

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: set Env value
        env:
          TZ: "Asia/Tokyo" # タイムゾーン指定
        run: |
          echo "process_date=`date '+%Y-%m-%d %H:%M:%S'`" >> "$GITHUB_ENV"

  pr_close:
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body , '/close')

    runs-on: ubuntu-latest

    steps:
      # - name: comment
      #   uses: actions/github-script@v6.4.1
      #   env:
      #     MESSAGE: |
      #       プルリクエストをクローズします
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     result-encoding: string
      #     retries: 3
      #     script: |
      #       const processDate = new Date().toLocaleString("ja")
      #       await github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: |
      #           process.env.MESSAGE
      #           "日時：" + processDate
      #       })
      #       await github.rest.issues.addLabels({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         labels: [
      #           'Test'
      #         ]
      #       })

      - name: close
        run: |
          gh pr close ${{env.PR_NUMBER}} \
          --comment "$MESSAGE"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          echo "Test"
