name: PR Comment Command

on:
  issue_comment:
    types:
      - created
      - edited

# 参考
# https://akaimo.hatenablog.jp/entry/2020/05/16/101251
# https://buildersbox.corp-sansan.com/entry/2021/02/05/110000

jobs:
  pr_command:
    name: close
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body , '/close')

    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: |
          echo "TEST"
